#!/usr/bin/env python3
"""Generate the deterministic, project-owned feasibility fixture."""

from __future__ import annotations

import argparse
import hashlib
import math
import struct
import wave
from pathlib import Path

SAMPLE_RATE = 44_100
CHANNELS = 2
SAMPLE_WIDTH_BYTES = 2
DEFAULT_DURATION_SECONDS = 8.0


def generate_fixture(path: Path, duration_seconds: float = DEFAULT_DURATION_SECONDS) -> dict[str, object]:
    """Write a deterministic stereo signal and return its stable identity."""
    if duration_seconds <= 0:
        raise ValueError("duration_seconds must be positive")

    path.parent.mkdir(parents=True, exist_ok=True)
    frame_count = round(SAMPLE_RATE * duration_seconds)

    with wave.open(str(path), "wb") as output:
        output.setnchannels(CHANNELS)
        output.setsampwidth(SAMPLE_WIDTH_BYTES)
        output.setframerate(SAMPLE_RATE)

        frames = bytearray()
        for index in range(frame_count):
            t = index / SAMPLE_RATE

            # A deterministic vocal-like harmonic stack with a slow envelope.
            envelope = 0.45 + (0.35 * math.sin(2 * math.pi * 1.7 * t))
            vocal = envelope * (
                0.34 * math.sin(2 * math.pi * 220 * t)
                + 0.18 * math.sin(2 * math.pi * 440 * t)
                + 0.09 * math.sin(2 * math.pi * 660 * t)
            )

            # A separate tonal bed makes the input a non-trivial two-source mix.
            bed_left = 0.19 * math.sin(2 * math.pi * 110 * t) + 0.12 * math.sin(2 * math.pi * 880 * t)
            bed_right = 0.19 * math.sin(2 * math.pi * 110 * t) + 0.12 * math.sin(2 * math.pi * 554.37 * t)
            left = max(-1.0, min(1.0, vocal + bed_left))
            right = max(-1.0, min(1.0, (vocal * 0.97) + bed_right))
            frames.extend(struct.pack("<hh", round(left * 32767), round(right * 32767)))

        output.writeframes(frames)

    payload = path.read_bytes()
    return {
        "name": "musicmute-owned-synthetic-v1",
        "sha256": hashlib.sha256(payload).hexdigest(),
        "bytes": len(payload),
        "sample_rate_hz": SAMPLE_RATE,
        "channels": CHANNELS,
        "sample_width_bytes": SAMPLE_WIDTH_BYTES,
        "frames": frame_count,
        "duration_seconds": frame_count / SAMPLE_RATE,
        "rights": "Generated by this repository; no third-party audio is included.",
    }


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("path", type=Path)
    parser.add_argument("--duration-seconds", type=float, default=DEFAULT_DURATION_SECONDS)
    args = parser.parse_args()
    identity = generate_fixture(args.path, args.duration_seconds)
    for key, value in identity.items():
        print(f"{key}={value}")


if __name__ == "__main__":
    main()
