org.gradle.jvmargs=-Xmx3g -Dfile.encoding=UTF-8
android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true
authApiUrl=https://api.music-mute.com
privacyUrl=https://api.music-mute.com/privacy
deletionUrl=https://api.music-mute.com/delete-account
supportUrl=https://api.music-mute.com/support
